services:
  ddrawry-be:
    container_name: 'ddrawry-be'
    build:
      context: .
    ports:
      - '8000:8000'
    restart: always
    volumes:
      - ./log/gunicorn:/log
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - JWT_SECRET=${JWT_SECRET}
