"""empty message

Revision ID: 26386dc9b1e5
Revises: 95334e178794
Create Date: 2024-10-09 23:38:45.913091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '26386dc9b1e5'
down_revision: Union[str, None] = '95334e178794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_diary', sa.Column('status', sa.Boolean(), nullable=False))
    op.drop_column('temp_diary', 'is_deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_diary', sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('temp_diary', 'status')
    # ### end Alembic commands ###
