"""Add temp_diary_id column to Image model

Revision ID: 518a186e779f
Revises: c20c21a78ddd
Create Date: 2024-10-13 22:55:53.162870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '518a186e779f'
down_revision: Union[str, None] = 'c20c21a78ddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('temp_diary_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'image', 'temp_diary', ['temp_diary_id'], ['id'])
    op.add_column('temp_diary', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temp_diary', 'image')
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.drop_column('image', 'temp_diary_id')
    # ### end Alembic commands ###
