"""empty message

Revision ID: 5c2e83b2025b
Revises: 98f0c2652d75
Create Date: 2024-10-13 22:46:22.164400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c2e83b2025b'
down_revision: Union[str, None] = '98f0c2652d75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_diary', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temp_diary', 'image')
    # ### end Alembic commands ###
