"""empty message

Revision ID: 6172d064e7c2
Revises: 019ca9755e8b
Create Date: 2024-10-03 20:31:51.691147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6172d064e7c2'
down_revision: Union[str, None] = '019ca9755e8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diary', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('diary', 'like',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diary', 'like',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('diary', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    # ### end Alembic commands ###
