"""Initial migration

Revision ID: 7e02af9644c9
Revises: ff4c8c0f7c81
Create Date: 2024-11-10 09:47:12.142324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7e02af9644c9'
down_revision: Union[str, None] = 'ff4c8c0f7c81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'temp_diary_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'temp_diary_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
