"""empty message

Revision ID: 95334e178794
Revises: 3960e65a1cdc
Create Date: 2024-10-06 23:22:09.389636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '95334e178794'
down_revision: Union[str, None] = '3960e65a1cdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('temp_diary', 'diary_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('temp_diary', 'diary_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
