"""empty message

Revision ID: 98f0c2652d75
Revises: d4c2c2f6ebff
Create Date: 2024-10-13 22:44:44.156134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98f0c2652d75'
down_revision: Union[str, None] = 'd4c2c2f6ebff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_diary', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temp_diary', 'image')
    # ### end Alembic commands ###
