"""Add kakao refresh token field

Revision ID: a2d7f6db6e7c
Revises: 7e02af9644c9
Create Date: 2024-11-11 18:02:27.609911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2d7f6db6e7c'
down_revision: Union[str, None] = '7e02af9644c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('refresh_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token', 'refresh_token')
    # ### end Alembic commands ###
