"""empty message

Revision ID: d4c2c2f6ebff
Revises: 617dc1d02b91
Create Date: 2024-10-13 22:43:38.025703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4c2c2f6ebff'
down_revision: Union[str, None] = '617dc1d02b91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_diary', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temp_diary', 'image')
    # ### end Alembic commands ###
