"""empty message

Revision ID: d80c8942bf5d
Revises: 9084ba8f2202
Create Date: 2024-10-11 00:12:44.986545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd80c8942bf5d'
down_revision: Union[str, None] = '9084ba8f2202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('delete_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'delete_at')
    # ### end Alembic commands ###
