"""empty message

Revision ID: ddc7f0bbc1b9
Revises: e440c923293b
Create Date: 2024-10-06 17:37:55.616486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ddc7f0bbc1b9'
down_revision: Union[str, None] = 'e440c923293b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diary', 'content')
    op.add_column('temp_diary', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('temp_diary', sa.Column('nickname', sa.String(length=100), nullable=True))
    op.add_column('temp_diary', sa.Column('story', sa.Text(), nullable=True))
    op.add_column('temp_diary', sa.Column('like', sa.Boolean(), nullable=False))
    op.alter_column('temp_diary', 'weather',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('temp_diary', 'mood',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('temp_diary', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False)
    op.alter_column('temp_diary', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False)
    op.alter_column('temp_diary', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_column('temp_diary', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_diary', sa.Column('content', mysql.TEXT(), nullable=True))
    op.alter_column('temp_diary', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('temp_diary', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('temp_diary', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('temp_diary', 'mood',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('temp_diary', 'weather',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('temp_diary', 'like')
    op.drop_column('temp_diary', 'story')
    op.drop_column('temp_diary', 'nickname')
    op.drop_column('temp_diary', 'date')
    op.add_column('diary', sa.Column('content', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
