"""Initial migration

Revision ID: ff4c8c0f7c81
Revises: 5af0b42a9743
Create Date: 2024-11-07 18:09:57.006588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ff4c8c0f7c81'
down_revision: Union[str, None] = '5af0b42a9743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'diary_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('image', 'temp_diary_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'temp_diary_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('image', 'diary_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
